[package]
name = "smb1-tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.58"
md5 = "0.7.0"
rhexdump = "0.1.1"
